name: trial-app

on:
  push:
    branches:
        - dev
    tags:
        - '*'

env:
    IMAGE_NAME: ghcr.io/${{github.repository_owner}}/trial-app
    IMAGE_ID: container_image
    APP_VERSION: 0.0.0

jobs:
   build-image:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Build the Docker image
        run: docker build . --file Dockerfile -t "${{env.IMAGE_NAME}}:${{github.ref_name}}"

      - name: Login to ghcr.io
        run: docker login ghcr.io -u "${{github.repository_owner}}" -p "${{secrets.owner_token}}"
    
      - name: Push image to ghcr.io
        run: docker push "${{env.IMAGE_NAME}}:${{github.ref_name}}"
